src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/order/dto/OrderHistory.java
src/main/java/lossleaderproject/back/order/dto/OrderRequest.java
src/main/java/lossleaderproject/back/order/entity/Orders.java
src/main/java/lossleaderproject/back/order/entity/StoreOrder.java
src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/store/dto/StoreRequest.java
src/test/java/lossleaderproject/back/order/service/OrderServiceTest.java

Add : 마이페이지 - 주문정보 리스트 페이징 처리

---

src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/dto/UserLoginIdFindRequest.java
src/main/java/lossleaderproject/back/user/dto/UserLoginIdResponse.java
src/main/java/lossleaderproject/back/user/dto/UserRequest.java
src/main/java/lossleaderproject/back/user/dto/UserResponse.java
src/main/java/lossleaderproject/back/user/entity/User.java
src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
src/main/java/lossleaderproject/back/user/repository/UserRepository.java
src/main/java/lossleaderproject/back/user/service/UserService.java
src/test/java/lossleaderproject/back/order/service/OrderServiceTest.java
src/test/java/lossleaderproject/back/user/service/UserServiceTest.java

Add : 아이디 찾기 API

---

build.gradle
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/dto/EMail.java
src/main/java/lossleaderproject/back/user/dto/EmailVerification.java
src/main/java/lossleaderproject/back/user/dto/EmailVerificationNumber.java
src/main/java/lossleaderproject/back/user/dto/SendEmail.java
src/main/java/lossleaderproject/back/user/dto/UserRequest.java
src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
src/main/java/lossleaderproject/back/user/service/MailService.java
src/main/java/lossleaderproject/back/user/service/UserService.java
src/main/resources/application.yml

markdown
- [] Jira에 맞는 적절한 브랜치를 생성했습니다
- [] PR 우측 Labels에서 적절한 라벨을 부착하였습니다.
- [] Commit 메세지 규칙에 맞게 작성했습니다.
- [] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.

Add : 이메일 설정 추가

---

.gitignore
src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/dto/UserFindPassword.java
src/main/java/lossleaderproject/back/user/dto/UserLoginIdFindRequest.java
src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
src/main/java/lossleaderproject/back/user/mail/dto/EMail.java
src/main/java/lossleaderproject/back/user/mail/dto/EmailVerification.java
src/main/java/lossleaderproject/back/user/mail/dto/EmailVerificationNumber.java
src/main/java/lossleaderproject/back/user/mail/dto/SendEmail.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/repository/UserRepository.java
src/main/java/lossleaderproject/back/user/service/UserService.java
src/main/resources/application.yml

Add : 비밀번호 찾기 API

---

src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/service/UserService.java

Add : 아이디 중복 검사 API

---

src/main/java/lossleaderproject/back/order/entity/Orders.java
src/main/java/lossleaderproject/back/order/repository/OrderRepository.java
src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
src/main/java/lossleaderproject/back/review/dto/ReviewRequest.java
src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
src/main/java/lossleaderproject/back/review/entity/Review.java
src/main/java/lossleaderproject/back/review/entity/ReviewImage.java
src/main/java/lossleaderproject/back/review/repository/ReviewImageRepository.java
src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
src/main/java/lossleaderproject/back/review/service/ReviewImageService.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java
src/main/java/lossleaderproject/back/store/controller/StoreController.java
src/main/java/lossleaderproject/back/store/dto/StoreHashTagRequest.java
src/main/java/lossleaderproject/back/store/dto/StoreMenuRequest.java
src/main/java/lossleaderproject/back/store/entitiy/StoreDetail.java
src/main/java/lossleaderproject/back/store/entitiy/StoreFoodImage.java
src/main/java/lossleaderproject/back/store/entitiy/StoreHashTag.java
src/main/java/lossleaderproject/back/store/entitiy/StoreMenu.java
src/main/java/lossleaderproject/back/store/repository/StoreFoodImageRepository.java
src/main/java/lossleaderproject/back/store/repository/StoreHashTagRepository.java
src/main/java/lossleaderproject/back/store/repository/StoreMenuRepository.java
src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
src/main/java/lossleaderproject/back/store/service/StoreDetailService.java
src/main/java/lossleaderproject/back/store/service/StoreFoodImageService.java
src/main/java/lossleaderproject/back/store/service/StoreHashTagService.java
src/main/java/lossleaderproject/back/store/service/StoreMenuService.java
src/main/java/lossleaderproject/back/store/service/StoreService.java
src/main/resources/application.yml

Add : 마이페이지 - 리뷰 API

---

src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
src/main/java/lossleaderproject/back/review/dto/ReviewRequest.java
src/main/java/lossleaderproject/back/review/service/ReviewImageService.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java
src/main/java/lossleaderproject/back/store/controller/StoreController.java
src/main/java/lossleaderproject/back/store/controller/StoreDetailController.java
src/main/java/lossleaderproject/back/store/dto/StoreListingResponse.java
src/main/java/lossleaderproject/back/store/dto/StoreMenuRequest.java
src/main/java/lossleaderproject/back/store/dto/StoreRequest.java
src/main/java/lossleaderproject/back/store/dto/StoreResponse.java
src/main/java/lossleaderproject/back/store/entitiy/Store.java
src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
src/main/java/lossleaderproject/back/store/service/StoreService.java

Fix:리스트 페이지 리스팅

---

src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/order/dto/OrderRequest.java
src/main/java/lossleaderproject/back/order/dto/PurchaseDetailsResponse.java
src/main/java/lossleaderproject/back/order/dto/PurchaseHistory.java
src/main/java/lossleaderproject/back/order/dto/PurchaseUserInfo.java
src/main/java/lossleaderproject/back/order/entity/Orders.java
src/main/java/lossleaderproject/back/order/entity/StoreOrder.java
src/main/java/lossleaderproject/back/order/repository/OrderRepository.java
src/main/java/lossleaderproject/back/order/repository/StoreOrderRepository.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/user/dto/UserRequest.java
src/test/java/lossleaderproject/back/order/service/OrderServiceTest.java

Add: 마이페이지 - 구매내역API 

---

src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java

Add 마이  페이지 리뷰 리스팅 API

---

Dockerfile
jenkins/Dockerfile
jenkins/docker_install.sh
src/main/java/lossleaderproject/back/store/controller/StoreController.java
src/main/java/lossleaderproject/back/store/dto/StoreDetailResponse.java
src/main/java/lossleaderproject/back/store/dto/StoreResponse.java

Fix: 메인페이지 res 변경

---

build.gradle
src/main/java/lossleaderproject/back/minio/ImageUtils.java
src/main/java/lossleaderproject/back/minio/MinioService.java
src/main/java/lossleaderproject/back/store/controller/StoreController.java
src/main/java/lossleaderproject/back/store/service/StoreFoodImageService.java
src/main/resources/application.yml

Add: 이미지 사이즈 리사이즈 4:3

---

build.gradle
src/main/java/lossleaderproject/back/minio/MinioService.java
src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
src/main/java/lossleaderproject/back/review/repository/ReviewRepository.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java
src/main/java/lossleaderproject/back/security/CorsConfig.java
src/main/java/lossleaderproject/back/security/oauth/provider/TokenProvider.java
src/main/java/lossleaderproject/back/store/controller/StoreController.java
src/main/java/lossleaderproject/back/store/repository/StoreRepository.java
src/main/java/lossleaderproject/back/store/service/StoreService.java
src/main/java/lossleaderproject/back/user/entity/User.java
src/main/java/lossleaderproject/back/user/service/UserService.java
src/main/resources-dev/application.yml
src/main/resources-prod/application.yml

Fix: 피드백 사항 반영

---

src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/order/dto/ProductOrder.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/security/CorsConfig.java
src/main/java/lossleaderproject/back/user/dto/UserRequest.java
src/main/java/lossleaderproject/back/user/dto/UserResponse.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/service/UserService.java

Fix : 회원,주문에 대한 리팩토링

---

src/main/java/lossleaderproject/back/order/dto/OrderHistory.java
src/main/java/lossleaderproject/back/order/entity/Orders.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewImageRequest.java
src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
src/main/java/lossleaderproject/back/review/entity/Review.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java
src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/dto/UserResponse.java
src/main/java/lossleaderproject/back/user/service/LoginService.java
src/main/java/lossleaderproject/back/user/service/UserService.java

Fix: 피드백 반영

---

src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/order/dto/OrderRequest.java
src/main/java/lossleaderproject/back/order/dto/OrderResponse.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/security/CorsConfig.java
src/main/java/lossleaderproject/back/security/oauth/provider/TokenProvider.java
src/main/java/lossleaderproject/back/user/controller/LoginController.java
src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/service/LoginService.java
src/main/resources-prod/application.yml

이메일 인증, 비밀번호 찾기

---

src/main/java/lossleaderproject/back/order/dto/OrderHistory.java
src/main/java/lossleaderproject/back/order/entity/Orders.java
src/main/java/lossleaderproject/back/order/service/OrderService.java

Fix:오더 리스팅 페이지 res 변경

---

src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/security/SecurityConfig.java
src/main/java/lossleaderproject/back/user/controller/LoginController.java
src/main/java/lossleaderproject/back/user/controller/UserController.java
src/main/java/lossleaderproject/back/user/dto/UserRequest.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/repository/UserRepository.java
src/main/java/lossleaderproject/back/user/service/LoginService.java
src/main/java/lossleaderproject/back/user/service/UserService.java

로그아웃, 정규식, 비밀번호 암호화, 회원가입 사용자 구별 리팩토링

Fix : 로그아웃, 정규식, 비밀번호 암호화, 회원가입 사용자 구별 리팩토링

---

build.gradle
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/security/SecurityConfig.java
src/main/java/lossleaderproject/back/user/controller/LoginController.java
src/main/java/lossleaderproject/back/user/exception/ErrorCode.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/repository/UserRepository.java
src/main/java/lossleaderproject/back/user/service/UserService.java

Fix : 리뷰 의존성 수정, 일반 회원 구별, 주문자 일치 여부

---

src/main/java/lossleaderproject/back/error/reviewException/ReviewControllerAdvice.java
src/main/java/lossleaderproject/back/error/reviewException/ReviewCustomException.java
src/main/java/lossleaderproject/back/error/reviewException/ReviewErrorCode.java
src/main/java/lossleaderproject/back/error/reviewException/ReviewErrorResponse.java
src/main/java/lossleaderproject/back/error/userException/UserControllerAdvice.java
src/main/java/lossleaderproject/back/error/userException/UserCustomException.java
src/main/java/lossleaderproject/back/error/userException/UserErrorCode.java
src/main/java/lossleaderproject/back/error/userException/UserErrorResponse.java
src/main/java/lossleaderproject/back/order/controller/OrderController.java
src/main/java/lossleaderproject/back/order/service/OrderService.java
src/main/java/lossleaderproject/back/review/controller/ReviewController.java
src/main/java/lossleaderproject/back/review/dto/ReviewResponse.java
src/main/java/lossleaderproject/back/review/service/ReviewService.java
src/main/java/lossleaderproject/back/security/exception/JwtExceptionFilter.java
src/main/java/lossleaderproject/back/security/jwt/JwtAuthorizationFilter.java
src/main/java/lossleaderproject/back/user/mail/service/MailService.java
src/main/java/lossleaderproject/back/user/service/UserService.java

Add: review exception 추가

---

.github/workflows/pr-test.yml

Add: git action yml file

---

src/main/java/lossleaderproject/back/user/dto/UserRequest.java

Fix : 회원가입시 주소 null 허용
